### ISSUE TITLE
todo-list

### ISSUE THREAD

**Issue by Lawliet-Chan** [yu-org/yu#2]
- [x] txpool persistence
- [x] preventing Replay Attack
- [ ] unit tests
   - [x] txpool test
   - [x] poa test
   - [x] blockchain test
   - [x] state test
   - [ ] subscribe test
   - [ ] p2p-network test
   - [ ] kernel run test
- [x] uncle blocks
- [ ] benchmark
- [ ] http api tests
- [x] clean codes
- [ ] vrf
- [ ] hotstuff
- [ ] browser
- [ ] go-SDK
- [ ] wallet
- [ ] eth smart contract tests
- [ ] multi-language template
